for %%I in ("%cd%") do set "serviceName=%%~nxI"
echo Deployin service %serviceName%...

echo Stopping service on server...
ssh Administrator@verisec.dedicated.co.za "sc stop %serviceName%"

echo Copying file to server...
scp %GOPATH%\bin\%serviceName%.exe Administrator@verisec.dedicated.co.za:.deploy/%serviceName%/bin/

echo Starting service on server...
ssh Administrator@verisec.dedicated.co.za "sc start %serviceName%"